### ISSUE TITLE
No password GUI when using *-pkexec commands

### ISSUE THREAD

**Issue by abickerton** [mate-desktop/mate-polkit#16]
When I try to access any application that uses policy kit I am not prompted to enter a password. Could you suggest where to start looking for the problem? 

I'm using LMDE with the SID repos.
mate-polkit, libmatepolkit  : 1.6.0-1+lmde
gir1.2-polkit-1.0                 : 0.112-2

In .xsession I'm seeing the following. 

** (polkit-mate-authentication-agent-1:4941): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine session the caller is in
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine session the caller is in

**Comment by monsta** [comment]
1.6.x is history, and 1.8.x is available in Jessie and Sid repos. Does it still happen there?

**Comment by NiceandGently** [comment]
@flexiondotorg 
no answer from reporter, please close it

**Comment by monsta** [comment]
@flexiondotorg: indeed, and the mentioned version is ancient
