### ISSUE TITLE
Consider deprecating this fork to reuse GNOME's polkit

### ISSUE THREAD

**Issue by TomWij** [mate-desktop/mate-polkit#17]
As we've (with stefano-k) spoken about in a query; could you look into whether it is possible to deprecate and remove the mate-polkit fork to reuse gnome-polkit, as well have the reverse dependencies use gnome-polkit?

Less packages translates to less maintenance at distributions.

Thank you very much in advance.

**Comment by NiceandGently** [comment]
This is bad!
gnome-shell doesn't use gnome-polkit anymore, means this is a death packages which is only use by gnome-flashback and will not get any love by mainly gnome devs anymore.

**Comment by NiceandGently** [comment]
Seems to be working in fedora, i only need to create a desktop file for autostart.
So +1 from me.

**Comment by flexiondotorg** [comment]
+1

**Comment by infirit** [comment]
It is up to the distro to make the decision, closing
