### ISSUE TITLE
when you move window,the focus will not focus on mate-polkit

### ISSUE THREAD

**Issue by HuangZhiquan** [mate-desktop/mate-polkit#19]
for example:
1.open launage-setting(anyone need authenaticate)
2.click "apply the whole system"
3.popup mate-polkit window,the focus on the gtkentry
4.cancell
5.move the window of launage-setting
6.do as step 2-3
7.the focus will not on mate-polkit
i donot know how to deal with this bug

**Comment by monsta** [comment]
Looks related to https://github.com/mate-desktop/marco/issues/117
