### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by blisbell** [mate-desktop/mate-polkit#20]
The last commit will no let it build errors with this. Building on Arch with http://pkgbuild.com/~flexiondotorg/mate-unstable-dual/1.9/x86_64/PKGBUILD/mate-polkit/PKGBUILD
 make[2]: *** No rule to make target 'kk.po', needed by 'kk.gmo'.  Stop.

**Comment by stefano-k** [comment]
https://github.com/mate-desktop/mate-polkit/commit/6caa50f630922597659d644258381b602715edbb
