### ISSUE TITLE
mate-polkit and GRSEC

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-polkit#29]
Today I did a quick test with mate-polkit on a GRSEC based Linux kernel.

By whatever reason, mate-polkit fails to start. More info, once I have rebooted into GRSEC kernel the next time.

**Comment by monsta** [comment]
Can you please also check whether policykit-1-gnome (of which mate-polkit is a fork) is affected as well?

**Comment by sunweaver** [comment]
STDOUT/ERR of various policykit agents:

RazorQt's polkit agent:

```
[mike@minobo ~]$ /usr/bin/razor-policykit-agent
Theme: Cannot open file for reading: "/usr/share/razor/themes/light/razor-policykit-agent.qss" 
New PolkitAgentListener  0x2221200 
Adding new listener  PolkitQt1::Agent::Listener(0x3c4b0ba3ee0) for  0x2221200 
"Cannot create unix session: No session for pid 5118" 

** (process:5118): CRITICAL **: polkit_agent_listener_register_with_options: assertion 'POLKIT_IS_SUBJECT (subject)' failed
"Cannot register authentication agent!" 

(process:5118): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
^C
```

MATE's PolKit Agent
```
[mike@minobo ~]$ mate-polkit
bash: /home/mike/bin/mate-polkit: /bin/bash: bad interpreter: Permission denied

```

GNOME's PolKit Agent:

```
[mike@minobo ~]$ /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

(polkit-gnome-authentication-agent-1:6091): polkit-gnome-1-WARNING **: Unable to determine the session we are in: No session for pid 6091

```

**Comment by sunweaver** [comment]
This happens on a Debian jessie system running mate-polkit 1.8.x (I know... don't frown... will test on Debian stretch system with MATE 1.14 soon...) and a 4.5.0 GRSEC Kernel from Debian jessie-backports.

**Comment by monsta** [comment]
Hmm... so that means all polkit agents fail?

**Comment by sunweaver** [comment]
On  Di 07 Jun 2016 09:53:49 CEST, monsta wrote:

> Hmm... so that means all polkit agents fail?
>


Yeah, looks like. Maybe this issue is non-existent in a more recent  
system. Debian jessie hadn't been made for GRSEC kernels, so let's see  
what happens when I test this on a more recent Debian system.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by monsta** [comment]
Yes, makes sense. Desktop environments are more recent in Testing/Unstable as well.

**Comment by monsta** [comment]
So, how's it going now (in various desktops)?

**Comment by monsta** [comment]
Ok, I'll close this for now, this weirdly named thing doesn't seem to make any difference anyway.
